package com.sanjay.aisecurity.controller;

import com.sanjay.aisecurity.common.ApiResponse;
import com.sanjay.aisecurity.constants.MessageConstants;
import com.sanjay.aisecurity.dto.response.ReportResponse;
import com.sanjay.aisecurity.service.ReportService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

/**
 * Controller for PDF report generation and management.
 *
 * @author Sanjay
 * @version 1.0.0
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/reports")
@RequiredArgsConstructor
@SecurityRequirement(name = "bearerAuth")
@Tag(name = "PDF Reports", description = "Endpoints for generating and downloading security reports.")
public class ReportController {

    private final ReportService reportService;

    @PostMapping("/generate/{scanId}")
    @Operation(summary = "Generate PDF report", description = "Generates a professional PDF security report for the specified scan.")
    public ResponseEntity<ApiResponse<ReportResponse>> generateReport(@PathVariable Long scanId) {
        log.info("REST request to generate PDF report for scan {}", scanId);
        ReportResponse response = reportService.generateReport(scanId);
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(ApiResponse.created(MessageConstants.REPORT_GENERATED, response));
    }

    @GetMapping("/{reportId}/download")
    @Operation(summary = "Download PDF report", description = "Downloads the physical PDF file for the specified report.")
    public ResponseEntity<Resource> downloadReport(@PathVariable Long reportId) {
        Resource resource = reportService.downloadReport(reportId);
        return ResponseEntity.ok()
                .contentType(MediaType.APPLICATION_PDF)
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=\"" + resource.getFilename() + "\"")
                .body(resource);
    }

    @GetMapping("/my")
    @Operation(summary = "List my reports", description = "Lists all PDF reports generated by the authenticated user.")
    public ResponseEntity<ApiResponse<List<ReportResponse>>> listMyReports() {
        List<ReportResponse> reports = reportService.listMyReports();
        return ResponseEntity.ok(ApiResponse.success(MessageConstants.SUCCESS, reports));
    }

    @GetMapping("/project/{projectId}")
    @Operation(summary = "Get project reports", description = "Lists all reports generated for a specific project.")
    public ResponseEntity<ApiResponse<List<ReportResponse>>> getProjectReports(@PathVariable Long projectId) {
        List<ReportResponse> reports = reportService.getProjectReports(projectId);
        return ResponseEntity.ok(ApiResponse.success(MessageConstants.SUCCESS, reports));
    }

    @DeleteMapping("/{reportId}")
    @Operation(summary = "Delete report", description = "Deletes a report and its physical file.")
    public ResponseEntity<ApiResponse<Void>> deleteReport(@PathVariable Long reportId) {
        reportService.deleteReport(reportId);
        return ResponseEntity.ok(ApiResponse.success(MessageConstants.REPORT_DELETED));
    }
}
