import { Link } from 'react-router-dom'
import { LuShieldCheck, LuTerminal, LuFileSearch, LuChevronRight } from 'react-icons/lu'

export default function LandingPage() {
  return (
    <div className="min-h-[100dvh] flex flex-col bg-surface-container-lowest font-['Manrope',sans-serif] overflow-x-hidden relative">
      {/* Background Pattern */}
      <div 
        className="absolute inset-0 pointer-events-none opacity-[0.03] z-0"
        style={{
          backgroundImage: `linear-gradient(to right, #0058be 1px, transparent 1px), linear-gradient(to bottom, #0058be 1px, transparent 1px)`,
          backgroundSize: '40px 40px'
        }}
      />
      <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-transparent pointer-events-none z-0" />

      {/* Header */}
      <header className="relative z-10 w-full px-6 py-5 flex items-center justify-between border-b border-outline-variant/30 bg-white/70 backdrop-blur-md">
        <div className="flex items-center gap-2">
          <img src="/logo.png" alt="CodeSentry" className="h-[36px] w-auto" />
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="text-sm font-semibold text-on-surface hover:text-primary transition-colors">
            Log In
          </Link>
          <Link to="/register" className="h-9 px-4 inline-flex items-center justify-center rounded-lg bg-primary text-white text-sm font-bold shadow hover:bg-primary/90 transition-colors">
            Get Started
          </Link>
        </div>
      </header>

      {/* Main Hero */}
      <main className="relative z-10 flex-1 flex flex-col items-center justify-center px-6 py-20 text-center">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider mb-8 border border-primary/20">
          <LuShieldCheck size={16} />
          AI-Powered Application Security
        </div>
        
        <h1 className="font-headline-lg text-4xl md:text-6xl font-extrabold tracking-tight text-on-surface max-w-[800px] leading-[1.1] mb-6">
          Secure your codebase with <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-blue-400">intelligent analysis.</span>
        </h1>
        
        <p className="text-base md:text-lg text-on-surface-variant max-w-[600px] mb-10 leading-relaxed">
          Upload source code, detect vulnerabilities automatically, and get AI-driven remediation guidance and professional security reports—all in one unified platform.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4">
          <Link to="/login" className="h-12 px-8 inline-flex items-center justify-center gap-2 rounded-xl bg-primary text-white text-base font-bold shadow-lg shadow-primary/20 hover:bg-primary/90 hover:scale-[1.02] transition-all">
            Start Scanning
            <LuChevronRight size={20} />
          </Link>
        </div>

        {/* Features Preview */}
        <div className="grid sm:grid-cols-2 gap-6 max-w-[700px] w-full mt-20 text-left">
          <div className="p-5 rounded-2xl bg-white border border-outline-variant/50 shadow-sm">
            <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
              <LuTerminal className="text-primary text-xl" />
            </div>
            <h3 className="font-bold text-on-surface mb-2">Static Analysis</h3>
            <p className="text-sm text-on-surface-variant leading-relaxed">Deterministic rule-based scanning identifies known vulnerability patterns instantly.</p>
          </div>
          <div className="p-5 rounded-2xl bg-white border border-outline-variant/50 shadow-sm">
            <div className="w-10 h-10 rounded-lg bg-green-500/10 flex items-center justify-center mb-4">
              <LuFileSearch className="text-green-600 text-xl" />
            </div>
            <h3 className="font-bold text-on-surface mb-2">AI Remediation</h3>
            <p className="text-sm text-on-surface-variant leading-relaxed">Understand complex flaws and receive exact code fixes generated by security-trained AI models.</p>
          </div>
        </div>
      </main>

      <footer className="relative z-10 w-full py-6 text-center text-sm text-on-surface-variant border-t border-outline-variant/30">
        &copy; {new Date().getFullYear()} CodeSentry Platform. All rights reserved.
      </footer>
    </div>
  )
}
